/**
 * @fileoverview gRPC-Web generated client stub for produit
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: produit.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.produit = require('./produit_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.produit.ProduitServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.produit.ProduitServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.produit.Empty,
 *   !proto.produit.ProduitList>}
 */
const methodDescriptor_ProduitService_GetAll = new grpc.web.MethodDescriptor(
  '/produit.ProduitService/GetAll',
  grpc.web.MethodType.UNARY,
  proto.produit.Empty,
  proto.produit.ProduitList,
  /**
   * @param {!proto.produit.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.produit.ProduitList.deserializeBinary
);


/**
 * @param {!proto.produit.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.produit.ProduitList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.produit.ProduitList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.produit.ProduitServiceClient.prototype.getAll =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/produit.ProduitService/GetAll',
      request,
      metadata || {},
      methodDescriptor_ProduitService_GetAll,
      callback);
};


/**
 * @param {!proto.produit.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.produit.ProduitList>}
 *     Promise that resolves to the response
 */
proto.produit.ProduitServicePromiseClient.prototype.getAll =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/produit.ProduitService/GetAll',
      request,
      metadata || {},
      methodDescriptor_ProduitService_GetAll);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.produit.Produit,
 *   !proto.produit.Produit>}
 */
const methodDescriptor_ProduitService_Create = new grpc.web.MethodDescriptor(
  '/produit.ProduitService/Create',
  grpc.web.MethodType.UNARY,
  proto.produit.Produit,
  proto.produit.Produit,
  /**
   * @param {!proto.produit.Produit} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.produit.Produit.deserializeBinary
);


/**
 * @param {!proto.produit.Produit} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.produit.Produit)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.produit.Produit>|undefined}
 *     The XHR Node Readable Stream
 */
proto.produit.ProduitServiceClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/produit.ProduitService/Create',
      request,
      metadata || {},
      methodDescriptor_ProduitService_Create,
      callback);
};


/**
 * @param {!proto.produit.Produit} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.produit.Produit>}
 *     Promise that resolves to the response
 */
proto.produit.ProduitServicePromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/produit.ProduitService/Create',
      request,
      metadata || {},
      methodDescriptor_ProduitService_Create);
};


module.exports = proto.produit;

